### ISSUE TITLE
Mixed Content

### ISSUE THREAD

**Issue by itsBen** [xpandit/tableau_write-back_extension#3]
Hey guys,

we set up the extension on our dev server for testing. It works flawlessly in Tableau Desktop, but as soon we publish the dashboard it doesn't. 

Chrome console says:
`Mixed Content: The page at 'url-to-dev*/#/views/Extension-WriteBackUseCase_V1/Dashboard1?:iid=5' was loaded over HTTPS, but requested an insecure resource 'http://xpandit.github.io/tableau_write-back_extension/html/'. This request has been blocked; the content must be served over HTTPS.`
at
`url-to-dev/views/Extension-WriteBackUseCase_V1/Dashboard1?:embed=y&:showVizHome=n&:toolbar=top&%3AopenAuthoringInTopWindow=true&%3AbrowserBackButtonUndo=true&%3AcommentingEnabled=true&%3AreloadOnCustomViewSave=true&%3AshowAppBanner=false&%3AisVizPortal=true&iframeSizedToWindow=true&:apiID=host0#5&navType=1&navSrc=Opt`

Tableau Server Version: `Tableau Server Version: 2018.2.0 (20182.18.0627.2230) 64-bit Windows`
Chrome: `Version 68.0.3440.106 (Offizieller Build) (64-Bit)`

Any advice ?

**Comment by rplp** [comment]
Hi Benedikt,

You are the first person to come across this issue so we are checking whether we need to change anything on the code to ensure https calls instead on http. Can you please send an email to to the contact indicated on the extension so we can further help you out. 

Regards,
Ricardo Pires

**Comment by itsBen** [comment]
Hey Ricardo,

could you please provide the email, I cannot seem to find it.

Another thing: I wanted to make sure I am on the latest version, so I downloaded from the gallery which says 1.0.0. In the extension about on desktop it says 0.5.0.  Is this correct ?

Thanks.
Ben

**Comment by rplp** [comment]
Hi,

You have the correct version. Not sure where the version from the gallery comes from. The email is 
![image](https://user-images.githubusercontent.com/1006570/44777567-e2883980-ab72-11e8-82ca-985ff797c06d.png)


Regards,
Ricardo Pires

**Comment by itsBen** [comment]
This might be related:

I set up a REST API to connect to a local sql server with endpoint: `http://localhost:3000/api/v1/writeback/updateAdd`

This works on Tableau Server with `Load unsafe script`. If I change the endpoint to `https` it doesnt work anymore. In Tableau Desktop neither of them works.

I will look into that and do some debugging... will keep you posted.
