### ISSUE TITLE
How can we use this to writeback to an Oracle DB

### ISSUE THREAD

**Issue by msacs09** [xpandit/tableau_write-back_extension#8]
Can you please advise on how can we leverage this code to writeback into a Oracle DB??

**Comment by rplp** [comment]
With this free extension you would need to code a backend that would allow you to get the requests from the extension and store on Oracle. If you don't want to go through that process we have a commercial version of Write-Back with corporate features that include, audit, on-prem deployment and support for multiple database technologies including Oracle. For more information you can check our website https://writeback4t.com/ .
